FROM docker.io/library/archlinux:latest

RUN pacman-key --init && pacman-key --populate archlinux 

RUN pacman -Syyu --noconfirm --needed npm fd ripgrep base-devel cmake vcpkg

RUN npm install -g @mariozechner/pi-coding-agent

WORKDIR /workdir
